var first_name = "Ranbir";
var last_name = "Kapoor";
first_name.concat(last_name);
var fullname = first_name.concat(last_name);
console.log(fullname);
var a = 10;
var b = 5;
var add = a + b;
console.log(add);
var subtract = a - b;
console.log(subtract);
var multiply = a * b;
console.log(multiply);
var divide = a / b;
console.log(divide);